site_name: CRT IH Documentation
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  features:
    - content.tabs.link
    - search.highlight
    - search.suggest
    - search.suggest
    
  language: en
  palette:
    - scheme: default
      toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
       icon: material/toggle-switch
       name: Switch to light mode
      primary: teal
      accent: lime
font:
  text: Roboto
  code: Roboto Mono
#favicon: assests/logo.png

nav:
   - Welcome: index.md
   - Technical Architecture:
   - Legacy Pattrens:
   - Datafeeds:
     - evergiving: datafeeds/evergiving.md
     - sugarcrm: datafeeds/sugarcrm.md
     - assemble: datafeeds/assemble.md
   - Deployments:
   - tools: 


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://google.com


copyright:
  copyright &copy; 2024 CRT