site_url: https://myrepo-doc-test.io/
site_author: repo user
site_name: myproject_github_pages
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
       icon: material/toggle-switch
       name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://google.com
    - icon: fontawesome/brands/twitter
      link: https://google.com
    - icon: fontawesome/brands/linkedin
      link: https://google.com



copyright:
  copyright &copy; 2024 myproject