site_name: myproject_github_pages  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  features:
    - content.tabs.link
    - search.highlight
    - search.suggest
    - search.suggest
    
  language: en
  palette:
    - scheme: default
      toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
       icon: material/toggle-switch
       name: Switch to light mode
      primary: teal
      accent: lime
font:
  text: Roboto
  code: Roboto Mono
#favicon: assests/logo.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://google.com
    - icon: fontawesome/brands/twitter
      link: https://google.com
    - icon: fontawesome/brands/linkedin
      link: https://google.com



copyright:
  copyright &copy; 2024 myproject